### ISSUE TITLE
Add permissive license to project

### ISSUE THREAD

**Issue by jereviikari** [mikepound/cubes#13]
I would like to request the addition of a permissive license to the project. Currently, the project does not have a clear licensing statement, which may restrict its usage and redistribution. By adding a permissive license, we aim to provide a legal framework that allows users to freely use, modify, and distribute the project with minimal restrictions.

**Comment by mikepound** [comment]
Hi, yes I will be adding a license. Likely ongoing changes will happen now in another repository, opencubes, which again will need a license.

**Comment by BartTerpstra** [comment]
Courtesy link to opencubes: https://github.com/mikepound/opencubes
